# Generated by Django 4.1.2 on 2022-10-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
