# Generated by Django 4.1.2 on 2022-10-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('Социальная жизнь', 'Социальная жизнь'), ('Учебные новости', 'Учебные новости'), ('Жизнь ВУЗа', 'Жизнь ВУЗа')], default='Социальная жизнь', max_length=32, verbose_name='Состояние заказа')),
            ],
        ),
    ]
