# Generated by Django 4.1.2 on 2022-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Картинка'),
        ),
    ]
