# Generated by Django 4.1.2 on 2022-10-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0003_customuser_type_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('', ''), ('vib12', 'ВИБ12'), ('vib22', 'ВИБ22')], default=' ', max_length=5, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('', ''), ('prepod', 'Преподаватель'), ('worker', 'Сотрудник')], default=' ', max_length=20, verbose_name='Тип'),
        ),
    ]
